apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-webapp
  template:
    metadata:
      labels:
        app: maven-webapp
    spec:
      containers:
      - name: maven-webapp
        image: rajratan26/maven-webapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: maven-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
