version: '3'

services:
  web:
    image: rajratan26/maven-webapp:latest
    container_name: my_web_app
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
